Algo & HF trading - P140

$\newcommand{\a}{\alpha} \newcommand{\s}{\sigma} \newcommand{\half}{\frac{1}{2}} \newcommand{\F}{\mathcal{F}} \newcommand{\P}{\mathbb{P}} \newcommand{\par}{\partial} \newcommand{\R}{\mathbb{R}} \newcommand{\argmin}{\arg\!\min} \newcommand{\E}{\mathbb E} \newcommand{\lb}{\left [} \newcommand{\rb}{\right ]} \newcommand{\U}{\mathcal{U}}$ $\newcommand{\lm}{\begin{pmatrix}} \newcommand{\rm}{\end{pmatrix}} \newcommand{\eps}{\varepsilon}$

The nonlinear PDE is given by
$$
    \partial_tH + \half \s^2 \partial_{ss}H + \frac{1}{4k}(S-\partial_q H)^2 = 0
$$
Consider the following BSDE representation
\begin{align}
    dX_t &= \lm dS_t \\ dQ_t \rm = \mu_t dt + \s_t dW_t \\
    dY_t &= -\frac{1}{4k}\lb a^T X_t - b^TAZ_t^T \rb^2 dt + Z_tdW_t, \quad g(Y_t) = -\infty \cdot \mathbb{1}_{Q_t>0}
\end{align}
where
$$
    \mu_t = \lm 0 \\ 0 \rm, \quad 
    \s_t= \lm \s_s & 0 \\ 0 & \varepsilon \rm, \quad 
    a = \lm 1\\ 0 \rm, \quad 
    b = \lm \half\\ \half \rm, \quad 
    A = \lm 0 & \frac{1}{\eps}\\ 0 & \frac{1}{\eps} \rm
$$

By generalized Feynman-Kac formula, we have

\begin{align}
    Y_t &= u(t, X_t ) \\
    Z_t &= D_x(t, X_t)\s_t
\end{align}

where $u(t, x)$ satisfies
\begin{align}
    && \par_t u(t, x) + \mathcal{L}u(t, x) + f(t, x, u(t, x), D_x(t, x)\s_t) = 0 \\
    &\iff& \par_t u(t, x) + \half\s_s^2\par_{ss}u(t, x) + \half\eps^2 \par_{qq}u(t, x) + f(t, x, u(t, x), D_x(t, x)\s_t) = 0 \\ 
    &\iff& \par_t u(t, x) + \half\s_s^2\par_{ss}u(t, x) + \half\eps^2 \par_{qq}u(t, x) + \frac{1}{4k}\lb a^Tx - b^TA (D_x(t,x)\s_t)^T \rb^2 = 0 \\
    &\iff& \par_t u(t, x) + \half\s_s^2\par_{ss}u(t, x) + \half\eps^2 \par_{qq}u(t, x) + \frac{1}{4k}\lb s - \lm 0 \\ \frac{1}{\eps}\rm^T \lm \s_s & 0 \\ 0 & \varepsilon \rm \lm \par_su \\ \par_qu \rm \rb^2 = 0\\
    &\iff& \par_t u(t, x) + \half\s_s^2\par_{ss}u(t, x) + \half\eps^2 \par_{qq}u(t, x) + \frac{1}{4k}\lb s -  \lm 0 \\ 1 \rm^T \lm \par_su \\ \par_qu \rm \rb^2 = 0\\
    &\iff& \par_t u(t, x) + \half\s_s^2\par_{ss}u(t, x) + \half\eps^2 \par_{qq}u(t, x) + \frac{1}{4k}\lb s - \par_q u(t, x) \rb^2 = 0\\
\end{align}

In [9]:
import numpy as np
dw = np.arange(4).reshape(2,2)
x = np.arange(5).reshape(1,5)

def d(data):
    for d in data:
        print(d)
        
d((dw, x))

[[0 1]
 [2 3]]
[[0 1 2 3 4]]


In [20]:
z = np.array([[1.],[2.]])

In [36]:
import tensorflow.experimental.numpy as tnp
import tensorflow as tf

In [26]:
z = tnp.array(z)

In [34]:
a = (tnp.ones([1, 2]) + tnp.ones([2, 1]))

In [45]:
b = tf.reduce_sum(a, 1)
b

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([4., 4.])>

In [52]:
c = tf.constant([[5.], [6.]], dtype='float64')
c

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.],
       [6.]])>

In [59]:
e = b + c
e

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 9.,  9.],
       [10., 10.]])>